### ISSUE TITLE
Review guide

### ISSUE THREAD

**Issue by niravassar** [micronaut-guides/micronaut-configuration#1]
This is a java guide and is on mn 1.2.5. ready to publish.

**Comment by ilopmar** [comment]
I've reviewed the guide and update a few things. It's already configured for Travis but we need to add the credentials to publish it to `gh-pages` branch.

I've also changed the date to a future one (in 1 year). @sdelamo can you please review and schedule the publication? Once it's ready I'll review and update the Groovy version.

**Comment by sdelamo** [comment]
I published the guide.
